services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appoinment_app
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: appoinment_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: appoinment_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appoinment_db
      MYSQL_USER: appoinment_user
      MYSQL_PASSWORD: appoinment_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: appoinment_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql_data: